spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  redis:
    host: localhost
    password:
    port: 6379
    lettuce:
      shutdown-timeout: 30000
      pool:
        max-active: 30
        max-idle: 8
        min-idle: 0
resilience4j:
  retry:
    instances:
      basic:
        maxRetryAttemps: 5
        waitDuration: 3s

  ratelimiter:
    instances:
      basicExample:
        limitForPeriod: 5
        limitRefreshPeriod: 4s
        timeoutDuration: 4s

management:
  endpoints:
    web:
      exposure:
        include: '*'
